name: Deploy Hugo Site to cPanel via FTP

on:
  push:
    branches:
      - main  # Menjalankan aksi saat ada perubahan pada branch utama (main)

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Hugo
      - name: Install Hugo
        run: |
          wget -qO- https://github.com/gohugoio/hugo/releases/download/v0.142.0/hugo_extended_0.142.0_linux-amd64.deb | sudo dpkg -i -
      
      # Build the site using Hugo
      - name: Build Hugo site
        run: hugo --minify --gc

      # Upload to cPanel via FTP
      - name: Upload to cPanel via FTP
        uses: samkirkland/ftp-deploy-action@4.1.0
        with:
          server: ${{ CPANEL.FTP_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./public/
          remote-dir: /public_html/  # Atau direktori lain yang diinginkan di cPanel
